spring:
  application:
    name: donations
  config:
    import: optional:configserver:http://localhost:8888

paypal:
  client-id: YOUR_CLIENT_ID
  client-secret: YOUR_CLIENT_SECRET
  mode: sandbox # or "live" for production
  return-url: http://localhost:8010/payment/success
  cancel-url: http://localhost:8010/payment/cancel