server:
  port: 8761  # Default Eureka port
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Don't register with itself
    fetch-registry: false       # Don't fetch registry from other servers
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
