spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      mvc:
        routes:
          - id: PetMs-pets
            uri: http://localhost:8050
            predicates:
              - Path=/api/v1/pet/**
          - id: PetMs-adoptionRequest
            uri: http://localhost:8050
            predicates:
              - Path=/api/v1/adoptionRequest/**
          - id: PetMs-petSittingOffer
            uri: http://localhost:8050
            predicates:
              - Path=/api/v1/petSittingOffer/**
          - id: PetMs-chatbot
            uri: http://localhost:8051
            predicates:
              - Path=/api/chat/**

level:
   org:
     springframework:
       cloud:
         gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true