spring:
  application:
    name: posts
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost}:8888
  main:
    allow-bean-definition-overriding: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: fureverbuddy93@gmail.com
    password: mwgizughkyacrmaz


    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

