eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: ${SERVER_PORT:8010}

spring:
  application:
    name: donations
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL:localhost:3306}/eventdonations?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  config:
    events-url: ${EVENT_SERVER_URL:http://localhost:8015}/event