eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Accept"
            allowCredentials: true
      routes:
        - id: posts
          uri: http://localhost:8082
          predicates:
            - Path=/api/services/**
        - id: appointments
          uri: http://localhost:8082
          predicates:
            - Path=/api/appointments/**

management:
  tracing:
    sampling:
      probability: 1.0