eureka:
  client:
    register-with-eureka: false

server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Accept"
<<<<<<< HEAD
=======
              - "Origin"
              - "X-Requested-With"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            exposedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Accept"
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
>>>>>>> 9d4586f5b7668b153416491cc882b700ec28816f
            allowCredentials: true
      routes:
        - id: services
          uri: http://localhost:8090
          predicates:
            - Path=/api/services/**
        - id: appointments
          uri: http://localhost:8091
          predicates:
            - Path=/api/appointments/**
<<<<<<< HEAD

=======
        - id: PetMs-pet
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/pet/**
        - id: PetMs-adoptionRequest
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/adoptionRequest/**
        - id: PetMs-petSittingOffer
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/petSittingOffer/**
        - id: PetMs-chatbot
          uri: http://localhost:8050
          predicates:
            - Path=/api/chat/**
>>>>>>> 9d4586f5b7668b153416491cc882b700ec28816f
management:
  tracing:
    sampling:
      probability: 1.0