spring:
  application:
    name: notification-ms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/notification_db?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_HOSTNAME:http://localhost}:8761/eureka

server:
  port: 8055

