eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8092

spring:
  application:
    name: notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notifications?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: firassbdh@gmail.com
    password: Tut28107403@@@
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

rabbitmq:
  exchanges:
    petservice: appointment.exchange
  queues:
    petservice: appointment.queue
  routing-keys:
    petservice: appointment.routingkey


management:
  tracing:
    sampling:
      probability: 1.0