eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8092

spring:
  application:
    name: notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/notifications?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

rabbitmq:
  exchanges:
    appointment: appointment.exchange
    petservice: petservice.exchange
  queues:
    appointment: appointment.queue
    petservice: petservice.queue
  routing-keys:
    appointment: appointment.routingkey
    petservice: petservice.routing-key

