eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:8014}

spring:
  application:
    name: payments
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:payments}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

stripe:
  api:
    key: ${STRIPE_API_KEY:sk_test_51RG5dVH61SNP6XKN7gIcOfs9sbqsfFGv7gt4R0UX7WsE9RemkJ5zDPhWqFLnit4sh3PxotpadPvnF1G8juE7w9YQ00Udt2ZC7I}
