eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8090

spring:
  application:
    name: services
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/services?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

rabbitmq:
  exchanges:
    petservice: petservice.exchange
  queues:
    petservice: petservice.queue
  routing-keys:
    petservice: petservice.routing-key

application:
  config:
    appointments-url: ${APPOINTMENT_URL:http://localhost}:8091/api/appointments

