spring:
  application:
    name: user_service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false


  security:
    jwt:
      secret-key: bXlzdXBlcnNlY3JldGtleXdoaWNoaXMyNTZiaXRzbG9uZ2FuZHNhZmU=
      expiration: 86400000

  mail:
    host: smtp.gmail.com
    port: "587"
    username: fureverbuddy93@gmail.com
    password: "ikqe nksu nqnq mnkc"
    admin:
      email: fureverbuddy93@gmail.com
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: "5000"
        timeout: "5000"
        writetimeout: "5000"


  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

app:
  admin:
    email: fureverbuddy93@gmail.com

server:
  port: 8084


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/