spring:
  application:
    name: user_service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/user_service?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  security:
    jwt:
      secret-key: ${JWT_SECRET:bXlzdXBlcnNlY3JldGtleXdoaWNoaXMyNTZiaXRzbG9uZ2FuZHNhZmU=}
      expiration: ${JWT_EXPIRATION:86400000}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:fureverbuddy93@gmail.com}
    password: ${MAIL_PASSWORD:mwgizughkyacrmaz}
    admin:
      email: ${ADMIN_EMAIL:fureverbuddy93@gmail.com}
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: "5000"
        timeout: "5000"
        writetimeout: "5000"

  mailing:
    frontend:
      activation-url: ${FRONTEND_URL:http://localhost}:4200/activate-account

app:
  admin:
    email: ${ADMIN_EMAIL:fureverbuddy93@gmail.com}

server:
  port: ${SERVER_PORT:8084}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_HOSTNAME:http://localhost}:8761/eureka/

application:
  config:
    pet-url: ${PET_SERVICE_URL:http://localhost}:8050