spring:
  application:
    name: PetMs
  config:
    import: optional:configserver:http://localhost:8888

  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet
  feign:
    hystrix:
      enabled: false
