spring:
  application:
    name: notification-ms
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  main:
    allow-bean-definition-overriding: true
    web-application-type: servlet

  profiles:
    active: default